# Generated by Django 3.2.3 on 2021-06-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=250)),
                ('teamImg', models.ImageField(upload_to='teampics')),
                ('teamdesc', models.TextField()),
            ],
        ),
    ]
